apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: customer1-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "8fffcdf6-d232-4faa-be30-6d62fdef31a9"
    keyvaultName: "kv-azure-staging"
    tenantId: "71db066c-474f-4adf-afc9-9609e2f6ae9d"
    objects: |
      array:
        - |
          objectName: customer1-db-user
          objectType: secret
        - |
          objectName: customer1-db-password
          objectType: secret
  secretObjects:
    - secretName: customer1-db-credentials
      type: kubernetes.io/basic-auth
      data:
        - objectName: customer1-db-user
          key: username
        - objectName: customer1-db-password
          key: password
    - secretName: customer1-n8n-env
      type: Opaque
      data:
        - objectName: customer1-db-user
          key: DB_POSTGRESDB_USER
        - objectName: customer1-db-password
          key: DB_POSTGRESDB_PASSWORD